spring.application.name=UrlShortener

spring.datasource.url=${DB_URL_JDBC}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.jpa.open-in-view=false

app.base-url=${BASE_URL}
spring.data.redis.url=${REDIS_URL}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
server.error.include-stacktrace=never