spring.application.name=UrlShortener

spring.datasource.url=jdbc:postgresql://ep-red-leaf-acaf7trm-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_W01bDJkLVvFc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

BASE_URL=${BASE_URL}
app.base-url=http://localhost:8080

spring.flyway.enabled=true
spring.jpa.open-in-view=false

